"""Safe, standard-library continuity primitives for agent project memory."""

from .config import (
    Config,
    ConfigLoadResult,
    RootClassification,
    classify_root,
    load_config,
    parse_toml_subset,
)
from .io import (
    PROCESS_LOCKING_AVAILABLE,
    AtomicWriteError,
    JsonReadResult,
    JsonlAppendError,
    ProcessLockError,
    append_jsonl,
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_text,
    ensure_private_directory,
    process_lock,
    process_lock_backend,
    read_json_state,
    write_json_state,
)
from .privacy import (
    PathClassification,
    PromptSummary,
    SensitiveScan,
    classify_sensitive_path,
    is_digest_only,
    scan_sensitive_text,
    summarize_prompt,
)

__all__ = [
    "Config",
    "ConfigLoadResult",
    "RootClassification",
    "PROCESS_LOCKING_AVAILABLE",
    "AtomicWriteError",
    "JsonReadResult",
    "JsonlAppendError",
    "ProcessLockError",
    "PathClassification",
    "PromptSummary",
    "SensitiveScan",
    "append_jsonl",
    "atomic_write_bytes",
    "atomic_write_json",
    "atomic_write_text",
    "classify_sensitive_path",
    "classify_root",
    "ensure_private_directory",
    "is_digest_only",
    "load_config",
    "parse_toml_subset",
    "process_lock",
    "process_lock_backend",
    "read_json_state",
    "scan_sensitive_text",
    "summarize_prompt",
    "write_json_state",
]
__version__ = "2.0.0.dev0"
